import { useState, useEffect } from 'react';
import { db, requestNotificationPermission } from './firebase.js';
import { collection, onSnapshot, doc, updateDoc, addDoc } from 'firebase/firestore';

const INITIAL_TASKS = [
  'Client onboarding call',
    'Send proposal',
      'Follow up email',
        'Update records',
          'Weekly report'
          ];

          export default function App() {
            const [tasks, setTasks] = useState([]);
              const [newTask, setNewTask] = useState('');
                const [notifEnabled, setNotifEnabled] = useState(false);

                  useEffect(() => {
                      const unsub = onSnapshot(collection(db, 'tasks'), (snap) => {
                            const data = snap.docs.map(d => ({ id: d.id, ...d.data() }));
                                  setTasks(data);
                                      });
                                          return unsub;
                                            }, []);

                                              async function addTask(title) {
                                                  await addDoc(collection(db, 'tasks'), { title, status: 'Pending' });
                                                    }

                                                      async function updateTask(id, status) {
                                                          await updateDoc(doc(db, 'tasks', id), { status });
                                                            }

                                                              async function handleEnableNotifs() {
                                                                  const token = await requestNotificationPermission();
                                                                      if (token) setNotifEnabled(true);
                                                                        }

                                                                          async function handleAddTask(e) {
                                                                              e.preventDefault();
                                                                                  if (!newTask.trim()) return;
                                                                                      await addTask(newTask.trim());
                                                                                          setNewTask('');
                                                                                            }

                                                                                              const statusColor = { 'Pending': '#F97316', 'In Progress': '#3B82F6', 'Done': '#22C55E' };

                                                                                                return (
                                                                                                    <div style={{ maxWidth: 480, margin: '0 auto', padding: 16, fontFamily: 'sans-serif' }}>
                                                                                                          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
                                                                                                                  <h1 style={{ color: '#F97316', margin: 0, fontSize: 22 }}>ArthSetu Checklist</h1>
                                                                                                                          {!notifEnabled && (
                                                                                                                                    <button onClick={handleEnableNotifs}
                                                                                                                                                style={{ background: '#F97316', color: 'white', border: 'none', borderRadius: 8, padding: '8px 14px', cursor: 'pointer', fontSize: 13 }}>
                                                                                                                                                            Enable notifs
                                                                                                                                                                      </button>
                                                                                                                                                                              )}
                                                                                                                                                                                      {notifEnabled && <span style={{ color: '#22C55E', fontSize: 13 }}>Notifs ON</span>}
                                                                                                                                                                                            </div>
                                                                                                                                                                                            
                                                                                                                                                                                                  <form onSubmit={handleAddTask} style={{ display: 'flex', gap: 8, marginBottom: 20 }}>
                                                                                                                                                                                                          <input value={newTask} onChange={e => setNewTask(e.target.value)}
                                                                                                                                                                                                                    placeholder="Add a task..."
                                                                                                                                                                                                                              style={{ flex: 1, padding: '10px 12px', borderRadius: 8, border: '1px solid #e5e7eb', fontSize: 14 }} />
                                                                                                                                                                                                                                      <button type="submit"
                                                                                                                                                                                                                                                style={{ background: '#F97316', color: 'white', border: 'none', borderRadius: 8, padding: '10px 16px', cursor: 'pointer', fontWeight: 'bold' }}>
                                                                                                                                                                                                                                                          Add
                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                        </form>
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                              {tasks.length === 0 && (
                                                                                                                                                                                                                                                                                      <div style={{ textAlign: 'center', color: '#9ca3af', padding: 40 }}>
                                                                                                                                                                                                                                                                                                <p>No tasks yet. Add your first task above!</p>
                                                                                                                                                                                                                                                                                                          <button onClick={() => INITIAL_TASKS.forEach(addTask)}
                                                                                                                                                                                                                                                                                                                      style={{ background: '#f3f4f6', border: '1px solid #e5e7eb', borderRadius: 8, padding: '8px 16px', cursor: 'pointer', fontSize: 13 }}>
                                                                                                                                                                                                                                                                                                                                  Load sample tasks
                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                {tasks.map(task => (
                                                                                                                                                                                                                                                                                                                                                                        <div key={task.id} style={{ background: 'white', border: '1px solid #e5e7eb', borderRadius: 12, padding: 16, marginBottom: 10, boxShadow: '0 1px 3px rgba(0,0,0,0.05)' }}>
                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ fontWeight: 500, fontSize: 15 }}>{task.title}</span>
                                                                                                                                                                                                                                                                                                                                                                                                          <span style={{ background: statusColor[task.status] || '#6b7280', color: 'white', borderRadius: 20, padding: '3px 10px', fontSize: 12 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                        {task.status}
                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ display: 'flex', gap: 6, marginTop: 10 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {['Pending', 'In Progress', 'Done'].map(s => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button key={s} onClick={() => updateTask(task.id, s)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{ flex: 1, padding: '6px 0', borderRadius: 6, border: '1px solid #e5e7eb', background: task.status === s ? statusColor[s] : '#f9fafb', color: task.status === s ? 'white' : '#374151', cursor: 'pointer', fontSize: 12, fontWeight: task.status === s ? 'bold' : 'normal' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {s}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
